name: Create AWS profile
description: Sets up an AWS profile in the file system
inputs:
  key:
    description: The AWS_ACCESS_KEY_ID
    required: true
  secret:
    description: The AWS_SECRET_ACCESS_KEY
    required: true
  profile:
    description: The profile name you want to setup
    required: true
  region:
    description: The AWS region you want to use
    required: true
runs:
  using: 'node12'
  main: 'index.js'