name: Create AWS profile
description: Sets up an AWS profile in the file system
inputs:
  key:
    description: The AWS_ACCESS_KEY_ID
    required: true
  secret:
    description: The AWS_SECRET_ACCESS_KEY
    required: true
  sessionToken:
    description: The AWS_SESSION_TOKEN
    required: false
  profile:
    description: The profile name you want to setup
    required: true
  aws_config_dir:
    description: The directory/folder where the AWS files will be saved
    required: false
  region:
    description: The AWS region you want to use
    required: true
runs:
  using: 'node16'
  main: 'index.js'
